services:
  postgresql:
    image: postgres:17
    environment:
      - 'POSTGRES_DB=spring26'
      - 'POSTGRES_USER=user'
      - 'POSTGRES_PASSWORD=pw'
    ports:
      - '5432:5432'
  garaged:
    build:
      context: ./garage
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3900:3900"
      - "3901:3901"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - ./garage/garage.toml:/etc/garage.toml
#    healthcheck:
#      test: [ "CMD", "garage", "status" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
