spring.application.name=spring26
gg.jte.developmentMode=true
spring.jpa.hibernate.ddl-auto=none
spring.docker.compose.lifecycle-management=start_only
# Visar exakt vad Spring Security gör med varje request
logging.level.org.springframework.security=TRACE
spring.jpa.show-sql=true
spring.sql.init.mode=always
server.forward-headers-strategy=framework
