<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form demo</title>
</head>
<body>
<h1>Form demo</h1>
<form method="POST" action="/books/form">
    <label for="name">Name:</label><br>
    <input id="name" type="text" name="name" placeholder="name"><br><br>
    <label for="email">Email:</label><br>
    <input id="email" type="email" name="email" placeholder="email"><br><br>
    <input type="submit" value="Submit">
</form>
</body>
</html>
