metadata_dir = "/tmp/meta"
data_dir = "/tmp/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "ca4191aa1c56ab8bdd1d085dc6898f87e35a500aa6d66e909073ca6d2772fb37"#"$(openssl rand -hex 32)"

[s3_api]
s3_region = "garage"
api_bind_addr = "[::]:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "[::]:3902"
root_domain = ".web.garage.localhost"
index = "index.html"

[k2v_api]
api_bind_addr = "[::]:3904"

[admin]
api_bind_addr = "[::]:3903"
admin_token = "wXKG9Bco1z9r5aA9385Y2fOy5OfeyM0rtb8/RJNP9Is="#"$(openssl rand -base64 32)"
metrics_token = "01RE6GPwmSeu0yXf80ZksUzTfbRNFh+FCJ3EnPXgIoE="#"$(openssl rand -base64 32)"
